name: AuctionHouse
version: '${project.version}'
main: me.outsid.auctionHouse.AuctionHouse
api-version: '1.21'
load: POSTWORLD

libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.45.1.0

commands:
  ahreload:
    description: Reload the AuctionHouse configuration
    permission: auctionhouse.admin
    usage: /ahreload
  auction:
    description: Open Auction
    usage: /<command> [sell <prix>]
    aliases: [ah]
  ecoadd:
    description: Add money (Console only)
    usage: /ecoadd <player> <amount>
  ecoset:
    description: Set player balance (Console only)
    usage: /ecoset
  money:
    description: Check your balance or another player's balance
    aliases: [bal, balance]
    usage: /money [player]
  pay:
    description: Send money to another online player
    usage: /pay <player> <amount>
  baltop:
    description: Display the wealthiest players
    aliases: [balancetop, topmoney]
    usage: /baltop
  
